# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import Client.App_view.resource_rc
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QStackedLayout
from PyQt5.QtWidgets import QApplication
from Client.App_view.View.write_email import Ui_Form

class Ui_MainWindow(QMainWindow):
    write_mail = QtCore.pyqtSignal()
    receive_mail = QtCore.pyqtSignal()
    address_book = QtCore.pyqtSignal()
    sent_mail = QtCore.pyqtSignal()
    trash_bin = QtCore.pyqtSignal()
    draft_box = QtCore.pyqtSignal()

    def __init__(self, parent=None):
        super(Ui_MainWindow, self).__init__(parent)
        self.setupUi(self)
        u = Ui_Form()
        self.qsl = QStackedLayout(self.frame)
        self.qsl.addWidget(u)
        self.connect_signal()

    def connect_signal(self):
        self.pushButton_2.clicked.connect(self.write_mail)
        self.pushButton_3.clicked.connect(self.receive_mail)
        self.pushButton_4.clicked.connect(self.address_book)
        self.pushButton_5.clicked.connect(self.sent_mail)
        self.pushButton_6.clicked.connect(self.trash_bin)
        self.pushButton_7.clicked.connect(self.draft_box)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 651)
        MainWindow.setMinimumSize(QtCore.QSize(953, 651))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("background-color:rgb(241, 241, 241)")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 951, 624))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_5 = QtWidgets.QSplitter(self.scrollAreaWidgetContents)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setHandleWidth(0)
        self.splitter_3.setObjectName("splitter_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 96))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(221, 96))
        self.scrollArea_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:none;\n"
"")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 221, 96))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label.setGeometry(QtCore.QRect(0, 10, 211, 81))
        self.label.setMaximumSize(QtCore.QSize(211, 81))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/img/标题.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.scrollArea_7 = QtWidgets.QScrollArea(self.splitter_3)
        self.scrollArea_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:none;")
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_10 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_10.setGeometry(QtCore.QRect(0, 0, 471, 96))
        self.scrollAreaWidgetContents_10.setObjectName("scrollAreaWidgetContents_10")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_10)
        self.lineEdit.setGeometry(QtCore.QRect(70, 30, 391, 41))
        self.lineEdit.setMinimumSize(QtCore.QSize(261, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgb(241, 241, 241)")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_10)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 41, 41))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-color:rgb(241, 241, 241)")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/img/放大镜.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_10)
        self.scrollArea_6 = QtWidgets.QScrollArea(self.splitter_4)
        self.scrollArea_6.setMinimumSize(QtCore.QSize(231, 96))
        self.scrollArea_6.setMaximumSize(QtCore.QSize(231, 96))
        self.scrollArea_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:none;")
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 231, 96))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 51, 51))
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/img/头像.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        self.label_4.setGeometry(QtCore.QRect(80, 30, 72, 15))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_8)
        self.comboBox.setGeometry(QtCore.QRect(76, 50, 151, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setEditable(False)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_8)
        self.pushButton.setGeometry(QtCore.QRect(150, 30, 52, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(10, 2, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(2, 194, 18);\n"
"    min-width: 2em;\n"
"    padding: 0px;    \n"
"    font: 75 9pt \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(10, 2, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_8)
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(False)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setMinimumSize(QtCore.QSize(222, 0))
        self.scrollArea_3.setMaximumSize(QtCore.QSize(222, 16777215))
        self.scrollArea_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:none;")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 222, 247))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 10, 161, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(10, 2, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 30px;\n"
"    border-color: rgb(2, 194, 18);\n"
"    \n"
"\n"
"\n"
"}\n"
"\n"
)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/img/写邮件_平时.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 90, 221, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton:focus{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(220, 0, 0);\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/img/收件箱.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 160, 221, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton:focus{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(235, 235, 0);\n"
"\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/img/通讯录.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_4.setObjectName("pushButton_4")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea_4.setMinimumSize(QtCore.QSize(222, 0))
        self.scrollArea_4.setMaximumSize(QtCore.QSize(222, 16777215))
        self.scrollArea_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:none;")
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 222, 247))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 20, 221, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton:focus{\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 170, 255);\n"
"\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/img/已发送_平时.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 80, 221, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton:focus{\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 170, 255);\n"
"\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/img/垃圾箱_平时.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 140, 221, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton:focus{\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 170, 255);\n"
"\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/img/草稿箱_平时.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon5)
        self.pushButton_7.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_7.setObjectName("pushButton_7")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.frame = QtWidgets.QFrame(self.splitter_2)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2.addWidget(self.splitter_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "搜索"))
        self.label_4.setText(_translate("MainWindow", "用户名"))
        self.pushButton.setText(_translate("MainWindow", "添加"))
        self.pushButton_2.setText(_translate("MainWindow", "   写邮件"))
        self.pushButton_3.setText(_translate("MainWindow", "   收件箱"))
        self.pushButton_4.setText(_translate("MainWindow", "   通讯录"))
        self.pushButton_5.setText(_translate("MainWindow", "  已发送"))
        self.pushButton_6.setText(_translate("MainWindow", "  垃圾箱"))
        self.pushButton_7.setText(_translate("MainWindow", "  草稿箱"))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = Ui_MainWindow()
    window.show()
    sys.exit(app.exec_())

