# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'read_email.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import base64
import json
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication
import Client.App_view.resource_rc
from PyQt5.QAxContainer import QAxWidget
from PyQt5.QtWidgets import QWidget, QVBoxLayout, QPushButton, QFileDialog, \
    QMessageBox
from PyQt5.QtWebEngineWidgets import *
from PySide2.QtWidgets import QLineEdit

from Client.App_view.View.Window import Window
from Client.Model.App_Model import App_Model
from Server.Utils.Receive_mail import ReceiveMailDealer


class Read_Form(Window):
    def __init__(self, parent=None):
        super(Read_Form, self).__init__(parent)
        self.setupUi(self)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(682, 466)
        Form.setMinimumSize(QtCore.QSize(682, 466))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(False)
        self.splitter.setHandleWidth(0)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 57))
        self.frame.setStyleSheet("background-color: rgb(109, 109, 109);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 680, 407))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_8 = QtWidgets.QSplitter(self.scrollAreaWidgetContents)
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName("splitter_8")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_8)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"background-color: transparent;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color:grey;\n"
"border:0px;\n"
"border-bottom: 2px solid #B3B3B3;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border-bottom: 3px solid #66A3FF;    \n"
"    }\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid #E680BD;    \n"
"    }")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"background-color: transparent;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color:grey;\n"
"border:0px;\n"
"border-bottom: 2px solid #B3B3B3;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border-bottom: 3px solid #66A3FF;    \n"
"    }\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid #E680BD;    \n"
"    }")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.textEdit = QWebEngineView(self.splitter_4)
        self.textEdit.setMinimumSize(658,248)
        self.lineEdit.setMaximumHeight(35)
        self.lineEdit_2.setMaximumHeight(35)


        # font = QtGui.QFont()
        # font.setFamily("微软雅黑")
        # font.setPointSize(14)
        # font.setBold(True)
        # font.setWeight(75)
        # self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("border:none;")
        self.textEdit.setObjectName("textEdit")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_8)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.line = QtWidgets.QFrame(self.splitter_7)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.splitter_8)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "新邮件"))
        self.lineEdit.setPlaceholderText(_translate("Form", "接收人"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "主题"))

    def show_mail(self, sender, title, content):
        self.lineEdit.setText(sender)
        self.lineEdit_2.setText(title)
        self.textEdit.setHtml(content)
        self.lineEdit.setDisabled(True)
        self.lineEdit_2.setDisabled(True)



if __name__ == '__main__':
    app = QApplication(sys.argv)

    rml = ReceiveMailDealer("zpl010720@qq.com", "esnkoqfbkduucejh")
    status, num = rml.search("All")
    newlist = num[0].split()

    mes = rml.getMailPartInfo(newlist[1])
    mes = {"mail": mes}

    message_bit = bytes(json.dumps(mes), encoding="utf8")

    message_bit = str(message_bit, 'utf8').replace("'", '"')
    mes = json.loads(message_bit,  strict=False)
    print(mes)
    window = Ui_Form()
    #
    #
    # print(mes)
    # # mes = "b'" + mes + "'"
    # print(mes)
    # mes = bytes(mes, encoding = 'utf8')
    # print(mes)
    mes = base64.b64decode(mes["mail"]["html"])
    print(mes)
    mes = str(mes, encoding = 'utf8')
    # print(mes)

    window.show_mail("fwse","fdwa",mes)
    window.show()
    sys.exit(app.exec_())

