# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'write_email.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication
import Client.App_view.resource_rc
from PyQt5.QAxContainer import QAxWidget
from PyQt5.QtWidgets import QWidget, QVBoxLayout, QPushButton, QFileDialog, \
    QMessageBox

from PySide2.QtWidgets import QLineEdit




class McomboBox(QtWidgets.QComboBox):
    def __init__(self, parent):
        super().__init__( parent)
        self.setAcceptDrops(True)
        self.file = {}

    def dragEnterEvent(self, e):
        if e.mimeData().hasText():
            e.accept()
        else:
            e.ignore()

    def dropEvent(self, e):
        filePathList = e.mimeData().text()
        filePath = filePathList.split('\n')[0] #拖拽多文件只取第一个地址
        filePath = filePath.replace('file:///', '', 1) #去除文件地址前缀的特定字符
        fileName = filePath.split("/")[-1]
        self.file[fileName] = filePath
        self.addItem(fileName)


class Ui_Form(QWidget):
    send_signal = QtCore.pyqtSignal()
    save_signal = QtCore.pyqtSignal()
    def __init__(self, parent=None):
        super(Ui_Form, self).__init__(parent)
        self.setupUi(self)
        self.connect_signal()
        self.axWidget = QAxWidget(self)
        self.pushButton_3.clicked.connect(self.onOpenFile)
        self.pushButton_4.clicked.connect(self.delitem)

    def delitem(self):
        self.comboBox.clear()
        self.comboBox.file = {}


    def onOpenFile(self):
        path, _ = QFileDialog.getOpenFileName(
            self, '请选择文件', '', 'excel(*.xlsx *.xls);word(*.docx);pdf(*.pdf);png(*.png);jpg(*.jpg);zip(*.zip)')
        if not path:
            return
        fileName = path.split("/")[-1]
        self.comboBox.addItem(fileName)
        self.comboBox.file[fileName] = path



    def connect_signal(self):
        self.pushButton_2.clicked.connect(self.send_signal)
        self.pushButton.clicked.connect(self.save_signal)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(701, 500)
        Form.setMinimumSize(QtCore.QSize(682, 466))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(False)
        self.splitter.setHandleWidth(0)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 57))
        self.frame.setStyleSheet("background-color: rgb(109, 109, 109);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 680, 407))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_8 = QtWidgets.QSplitter(self.scrollAreaWidgetContents)
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName("splitter_8")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_8)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"background-color: transparent;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color:grey;\n"
"border:0px;\n"
"border-bottom: 2px solid #B3B3B3;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border-bottom: 3px solid #66A3FF;    \n"
"    }\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid #E680BD;    \n"
"    }")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"background-color: transparent;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color:grey;\n"
"border:0px;\n"
"border-bottom: 2px solid #B3B3B3;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border-bottom: 3px solid #66A3FF;    \n"
"    }\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 3px solid #E680BD;    \n"
"    }")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.textEdit = QtWidgets.QTextEdit(self.splitter_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("border:none;")
        self.textEdit.setObjectName("textEdit")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_8)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.line = QtWidgets.QFrame(self.splitter_7)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_7)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setOpaqueResize(False)
        self.splitter_6.setHandleWidth(130)
        self.splitter_6.setChildrenCollapsible(False)
        self.splitter_6.setObjectName("splitter_6")
        self.frame_3 = QtWidgets.QFrame(self.splitter_6)
        self.frame_3.setStyleSheet("border:None;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/img/附件.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.comboBox = McomboBox(self.frame_3)
        self.comboBox.setGeometry(QtCore.QRect(30, 10, 111, 21))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 170, 255);\n"
"    \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"   background-color: rgb(145, 145, 145);\n"
"   }\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.pushButton = QtWidgets.QPushButton(self.splitter_5)
        self.pushButton.setMaximumSize(QtCore.QSize(131, 42))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(2, 194, 18);\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(2, 194, 18);\n"
"    min-width: 4em;\n"
"    padding: 6px;\n"
"    font: 75 11pt \"微软雅黑\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(2, 194, 18);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter_5)
        self.pushButton_2.setMaximumSize(QtCore.QSize(128, 42))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(10, 2, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(2, 194, 18);\n"
"    min-width: 4em;\n"
"    padding: 6px;    \n"
"    font: 75 11pt \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(10, 2, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.splitter_8)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "新邮件"))
        self.lineEdit.setPlaceholderText(_translate("Form", "接收人"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "主题"))
        self.pushButton_3.setText(_translate("Form", "选择"))
        self.pushButton_4.setText(_translate("Form", "删除"))
        self.pushButton.setText(_translate("Form", "存草稿"))
        self.pushButton_2.setText(_translate("Form", "发邮件"))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = Ui_Form()
    window.show()
    sys.exit(app.exec_())
